EXPORT_FUNC(get_version)
EXPORT_FUNC(getc)
EXPORT_FUNC(tstc)
EXPORT_FUNC(putc)
EXPORT_FUNC(puts)
EXPORT_FUNC(printf)
EXPORT_FUNC(install_hdlr)
EXPORT_FUNC(free_hdlr)
EXPORT_FUNC(malloc)
EXPORT_FUNC(free)
EXPORT_FUNC(udelay)
EXPORT_FUNC(get_timer)
EXPORT_FUNC(vprintf)
EXPORT_FUNC(do_reset)
#if (CONFIG_COMMANDS & CFG_CMD_I2C)
EXPORT_FUNC(i2c_write)
EXPORT_FUNC(i2c_read)
#endif	/* CFG_CMD_I2C */

#if 1 /*standalone download*/
EXPORT_FUNC(dl_GetAddr)
EXPORT_FUNC(dl_Initialize)
EXPORT_FUNC(ctrlc)
EXPORT_FUNC(AssignHWAddress)
EXPORT_FUNC(sprintf)
EXPORT_FUNC(setenv)
EXPORT_FUNC(dl_Transmit)
EXPORT_FUNC(reset)
EXPORT_FUNC(memcpy)
EXPORT_FUNC(memset)
EXPORT_FUNC(sc_xchg)
EXPORT_FUNC(dumpData)
EXPORT_FUNC(FlashDriver)
EXPORT_FUNC(memcmp)
EXPORT_FUNC(saveenv)
EXPORT_FUNC(NetLoop)
EXPORT_FUNC(delay_1s)
EXPORT_FUNC(ret_NetTxPacket)
#endif
